const GroupsData = [
  {
    id: 0,
    name: "Nkrasa PTC",
    institution: "Nkrasa Politechnic",
    leader: "Mr Anim George",
    depth: 45000,
    members: 8,
    month: "June",
    location: "Tesano",
    img: require("../assets/groups/0.jpg"),
  },
  {
    id: 1,
    name: "PWTC",
    institution: "Abeka Presbyterian Church",
    leader: "Mrs Rita Siaw",
    depth: 11000,
    members: 5,
    month: "July",
    location: "Lapaz",
    img: require("../assets/groups/1.jpg"),
  },
  {
    id: 2,
    name: "Delloite",
    institution: "Delloite Group of Companies",
    leader: "Mr Doodo Fredrick",
    depth: 102000,
    members: 20,
    month: "March",
    location: "Apenkwa",
    img: require("../assets/groups/2.jpg"),
  },
  {
    id: 3,
    name: "Rewdev",
    institution: "Renewed Offices",
    leader: "Mrs Frimpong",
    depth: 12563,
    members: 16,
    month: "November",
    location: "Tema com 5",
    img: require("../assets/groups/3.png"),
  },
];

export default GroupsData